# Generated by Django 2.2.1 on 2019-06-16 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlineapp', '0002_processinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processinfo',
            old_name='PID',
            new_name='pid',
        ),
    ]
