# Generated by Django 2.2.1 on 2019-06-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketstas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='umpire1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='umpire3',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
