# Generated by Django 2.2.1 on 2019-06-17 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketstas', '0003_auto_20190617_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='bastman',
            new_name='batsman',
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='bastman_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='bye_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='extra_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='is_super_over',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='legbye_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='nonball_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='penalty_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='total_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='wide_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='dl_applied',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='result',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='win_by_runs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='win_by_wickets',
            field=models.IntegerField(null=True),
        ),
    ]
