# Generated by Django 2.2.1 on 2019-06-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cricketstas', '0004_auto_20190617_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='bastman_runs',
            new_name='batsman_runs',
        ),
    ]
